### ISSUE TITLE
Would you mind adding a copyright / license header to index.ts?

### ISSUE THREAD

**Issue by trevorade** [mmkal/expect-type#11]
Thank you for authoring this library! I'd like to start using it in my work but want to make sure that we're attributing it correctly.

Can you please add a short copyright notice to the `index.ts` file?

---

Some examples:

```ts
// Copyright 2022 [name of copyright owner]
```

```ts
/**
 * Copyright 2022 [name of copyright owner]
 * @license Apache-2.0
 */
```

**Comment by mmkal** [comment]
Sorry, my reply to this didn't seem to get sent. I don't have any particular objection to this, but do you have an article/blog post explaining why this would be needed? I'd have thought the Apache license would be sufficient, and from a quick look at a random selection of other OSS repos, most don't have one baked into the actual code. Is there a tool you use that scans code for headers like this for an attribution page, or something?

**Comment by trevorade** [comment]
Yeah I agree with you. Most OSS does not do this.

When pulling in open source projects into my employer's codebase, we have a policy to add a `@license` block to the JS/TS files via some automation. We also specify the copyright in these comments. I didn't see any copyright for this project though so wanted to clarify on the status there.

At this point, I don't think this matters a ton for our particular usage of `expect-type`.

**Comment by mmkal** [comment]
I don't think I'll do this in that case!
