### ISSUE TITLE
Redonly should not match writable

### ISSUE THREAD

**Issue by qwelias** [mmkal/expect-type#23]
```ts
import {expectTypeOf} from 'expect-type'

const a = { foo: 1 }
const b = { foo: 1 } as Readonly<typeof a>

expectTypeOf(a).toMatchTypeOf<typeof b>()
expectTypeOf(b).toMatchTypeOf<typeof a>() // does not error, but should

a.foo = 2
b.foo = 2 // error, b.foo is readonly
```

**Comment by mmkal** [comment]
> expectTypeOf(b).toMatchTypeOf<typeof a>() // does not error, but should

Will have a think about whether I agree that it should. There's some discussion elsewhere about what exactly `toMatchTypeOf` means or should mean. But in the meantime, `toEqualTypeOf` is probably what you want here. It detects the difference between readonly properties.

**Comment by qwelias** [comment]
From the examples in the Readme I've got the impression that it should check for extesibility, e.g.:
`expectTypeOf(b).toMatchTypeOf<typeof a>() // typeof b extends typeof a`

If it isn't than what would be the right way to test whether `typeof b extends typeof a`?
And why shouldn't it given that `extends` is the core TS concept?

**Comment by mmkal** [comment]
That is how regular typescript works though isn't it? [demo](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhjAvDA3gMxCAXDAjAXwChRJYAjJVDbPfeCGAJQFM4ATcAGwE8AeKbgAdmINPAB8hYuGgwAHjgHDRMCszlRmYNgyUixCAPwwA5N2YQTMHCbAgryMxZPTSMboqH74MdZu26XipGpuaW1qZ2DqHOhEA)
