### ISSUE TITLE
[bug] Type of nested properties are not fully resolved and fail equality test.

### ISSUE THREAD

**Issue by gomain** [mmkal/expect-type#29]
```ts
{
  type ObjectWithProp<PROP> = {
    prop: PROP;
  };
  type MakeNestObject<NEST_OBJECT extends { nestProp: ObjectWithProp<any> }> = {
    nestObj: NEST_OBJECT;
  };

  /* as expected */
  expectTypeOf<
    MakeNestObject<{ nestProp: ObjectWithProp<"one"> }>
  >().toEqualTypeOf<{ nestObj: { nestProp: { prop: "one" } } }>();
  expectTypeOf<
    MakeNestObject<{ nestProp: ObjectWithProp<"two"> }>
  >().toEqualTypeOf<{ nestObj: { nestProp: { prop: "two" } } }>();

  /* but */
  expectTypeOf<
    MakeNestObject<{ nestProp: ObjectWithProp<"one"> }>
  >().toEqualTypeOf<MakeNestObject<{ nestProp: ObjectWithProp<"two"> }>>();

  /* assignability test, the old fashion way */
  let o1: MakeNestObject<{ nestProp: ObjectWithProp<"one"> }> = null as any;
  let o2: MakeNestObject<{ nestProp: ObjectWithProp<"two"> }> = null as any;
  // @ts-expect-error - type "two" is not assignable to type "one"
  o1 = o2;
  // @ts-expect-error - type "one" is not assignable to type "two"
  o2 = o1;

  /* if the nested object type were by different name */
  type AnotherName<PROP> = {
    prop: PROP;
  }
  expectTypeOf<
    MakeNestObject<{ nestProp: ObjectWithProp<"one"> }>
  >().toEqualTypeOf<MakeNestObject<{ nestProp: AnotherName<"one"> }>>();
  expectTypeOf<
    MakeNestObject<{ nestProp: ObjectWithProp<"one"> }>
  >().not.toEqualTypeOf<MakeNestObject<{ nestProp: AnotherName<"two"> }>>();
}
```
[**Playground**](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUwB5mQYxgFQJ4YDyAZnAL5zFQQhwBEaG2AtDAcnQNwBQ3C3cOGwxxCAIwBWWGAHVgMABYAFamAA8SgEqElAPjgBeRAMFwwqgFxwtOnoLJ2h7OAFkAhgGtkAOWQBnGHEpbDVvAFEAZRwAfUIAIQApMIBhHBRUGGQAOwATP0Q4LP8YFQgwKyDpOUVS9TcsvH0yfSN+U0LioKtwqNjElJxHB15BAHoAKjg3fMZpZBy4cdGTWex8ImI1E0F3L18AypCkIoDaiskq+WVVNToIIrom3RNdAAoASgA6GAgwgEcAK5uAA262QJDUx06kisUNOlgK5jKVjuD3I6OaH0cq1w7Ah21cnh80OCMEhHXhyNEF2w1WuZVuMAA7hBHuRnoI3l8fv8gaC8Zs4YEYQUTiUEUgkeV6MzWRj2ViRnAJnAxAD4EsVuhpGD8e1dsSDjSyUKztTSXTard7hwni8Pt9foCQbrNgb9sLSeSxWbDrIrla6LK2c0uY4TCrpn5gABzLJuMTAYHyPBCYoAGiECmQcAgwIWxGmCmA9zgTLcqc1gmByHgEAAjFZ3STpN7ir7jZabqjbezDIUAcDgVN8vU8I4a3WAExNokev1tynSv1dhlBlkhloDocjqYNRyjUZwAACMD8zBxF6g1CgcGYThE67lwHyWQg8CjsfjYhrQggD5zHs6BMBt+wgKcDyPU9z0vZBr2gO8APoG06DgF9CnfEdozjBNfx+JCn2AwRwLA+seAjSZgFIRQczFeZc2NJCmTgnMxFTHIqOIFisngeMQBzKskIAQTfGioG8Nx+I0bQ9H7NpTClKwbCUIYtSYXENi2fU5xbI4KXFKkVwDbsULtTkHR5Z1+U05sjS9U0ERE99s3EyTkGtB4njDNSdQFLTTFsz1WwcwzO2MtdTPZe0vlEx1eRdPzAoXELpScsSJKkwivMVMggA)

**Comment by gomain** [comment]
This may be a related use case:
```ts
  expectTypeOf<number[]>().toEqualTypeOf<any[]>(); // passes
```

**Comment by mmkal** [comment]
@gomain yes, this is a bug - those definitely shouldn't pass.
