### ISSUE TITLE
Thank you for making this library

### ISSUE THREAD

**Issue by webNeat** [mmkal/expect-type#3]
Hello,

This is not an issue, I just wanted to thank you for making this library. I learned many things by reading the source code. In particular I liked the `DeepBrand` type.

I was using the following simple custom types to unit test types

```ts
export type Is<T extends true> = T
export type Equal<X, Y> = Exclude<X, Y> | Exclude<Y, X> extends never ? true : false

// To test that two types A and B are equal, I do
type Test = Is<Equal<A, B>>
```

As you see, this works for simple cases, but will fail to check optional properties for example ...

I will be using this library instead :)

Feel free to close this issue once you read it ;)

**Comment by mmkal** [comment]
Thanks, much appreciated!
