### ISSUE TITLE
Expose "toExtend" functions

### ISSUE THREAD

**Issue by JacobLey** [mmkal/expect-type#36]
Alongside the existing `ExpectTypeOf` methods, a method to check for successful extension of types would be helpful. Perhaps a strict/branded version as well.

Proposed syntax:
```
expectTypeOf<5>().toExtend<number>();
expectTypeOf<unknown>().toExtend<any>();
expectTypeOf('abc').toExtend([{}]); // Typescript error

expectTypeOf<5>().toStrictExtend<number>();
expectTypeOf<unknown>().toStrictExtend<any>(); // Typescript error
expectTypeOf('abc').toStrictExtend([{}]); // Typescript error
```

I would be happy to submit a PR for this. Especially since the `Extends` and `StrictExtends` types are already implemented, just not directly exposed in the main method.

My current workaround is:
```
expectTypeOf<
     StrictExtends<Foo, Bar>
>().toBeEqual<true>();
```

Admittedly the grammar is a bit different (most methods start with `toBe`) so open to a renaming to match. `toBeExtending`...?

**Comment by JacobLey** [comment]
Ah I think I was confused reading through code.

Looks like this is effectively `toMatchTypeOf`, which is _always_ the non-strict type.

I guess the followup is instead to support the strict "branded" version of `toMatchTypeOf` (similar to `branded.toEqualTypeOf`)

**Comment by mmkal** [comment]
This is `toMatchTypeOf`, but I am considering deprecating `toMatchTypeOf` in favour of something like `toExtend` (probably making `toMatchTypeOf` an alias). Similarly I might rename `toEqualTypeOf` to be some kind of `toBeIdenticalTo`. But, for now, use `toMatchTypeOf`. I'll leave this open until that happens (or I decide definitively not to do that).
