### ISSUE TITLE
[expect-type] expectTypeOf(this).to{Equal,Match}TypeOf(this) fails

### ISSUE THREAD

**Issue by NullVoxPopuli** [mmkal/expect-type#4]
Here is a [TS Playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUwB5mQYxgFQJ4YDyAZnAL5zFQQhwDkaG2AtDAcnQNwBQ3j08NhjgBhCADsYaGCQA8ASXEBnGAENxmZAD44AXm5w4iles0pUU8QBMlcABQA6J6qgBzJQC4445ADdkUADaALoAlHo6AK7iANbiEADu4gaGcAD83n4BKYZexmoayLzcmAA2qkq2AIKIKap6cACMPGS8jFi47HJiktJyVVpadqEOMBAAogCOkaql+ETEsgPDPO3Y88jdElIWcsMR9kjEEBBe4pEgAEYB5KGDw6MT07Mbcj7+UEOhPHzoAnBlCq2ABCtUMlwaACJLpCfoZMBIVFBIthoPsEDk4KVkPBUA0YAALYBKHipcxMToLWRCZAQUioL6PACyqhgmAJr0WNLpcAZKxSrRSrhxlBO6Mx2Nx+KJJMxa0pm2IdkJxJGYymMzmXSVKqU3zl6A6nOVMrVEBZbI52pNqtJqXlnOp7B5fLNFvZju59K+dsMUBxkSg4nJRu1sh6OxkXOd3sZY3dVqpXt5PoF3DIQA) and [related StackOverflow post](https://stackoverflow.com/questions/73602871/how-do-you-conditionally-type-between-a-function-and-an-instance-of-a-class)

And the sample code:

```ts
export class B {
  b = "b";
  
  get foo() {
    expectTypeOf(this).toEqualTypeOf(this); // errors
    expectTypeOf(this).toMatchTypeOf(this); // errors
  }
}
```

Hovering over the `toEqualTypeOf` call provides this information:
```
(property) ExpectTypeOf<this, true>.toEqualTypeOf: <unknown>(...MISMATCH: MismatchArgs<And<[Extends<DeepBrand<this>, {
    type: "special";
    never: false;
    any: false;
    unknown: true;
}>, {
    type: "special";
    never: false;
    any: false;
    unknown: true;
} extends DeepBrand<...> ? true : false]>, true>) => true (+1 overload)

--- 

No overload matches this call.
  Argument of type '[this]' is not assignable to parameter of type 
    'MismatchArgs<
      And<
        [
          Extends<
            DeepBrand<this>, 
            { 
              type: "special"; 
              never: false; 
              any: false; 
              unknown: true; 
            }
          >, 
          { 
            type: "special"; 
            never: false; 
            any: false; 
            unknown: true; 
          } extends DeepBrand<...> 
            ? true 
            : false
        ]
      >, 
      true
    >'.
  
Argument of type '[]' is not assignable to parameter of type   
  'MismatchArgs<
    And<
      [
        Extends<DeepBrand<this>, DeepBrand<this>>, 
        Extends<DeepBrand<this>, DeepBrand<this>>
      ]
    >, 
    true
  >'.(2769)
```

**Comment by mmkal** [comment]
@NullVoxPopuli thanks for this report. I'm not sure why this would be but I doubt it'll be possible to resolve. #16 will add some docs covering this.
