### ISSUE TITLE
`.omit` does not work with unions

### ISSUE THREAD

**Issue by mrazauskas** [mmkal/expect-type#53]
[Playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwKYA8xIMYwCoE90DyAZgL5xFQQhwDkq6WAtDPkjQFDsvpwAyEAQwAmwAHYBzOAF5E7OHADOMATCQAuOACIANoJETNAbnYlj3JHABiA4NqRDps+UpXqtRG3aFG5cDBCE3UQBXEAAjJChjU056TBxWYgAefmExSQAfK097AD4ACgBKADoqYBgkmn9AmgKSmAgAUQBHYIFtPEIiJIQXVQ0aXTSJGjgsmg9bexoSOvY4rE6kZIIQcpS9dLHsqaEAGlpqtly64oaWto7E7t7lftoh-XFR8cmvGbmgA).

Take a look at the following example. `Omit` works as expected, but `.omit` fails:

```ts
import {expectTypeOf} from 'expect-type'

type Loading = {
  state: "loading";
};
type Failed = {
  state: "failed";
  code: number;
};

expectTypeOf<Omit<Loading | Failed, 'code'>>().toEqualTypeOf<{state: 'loading' | 'failed'}>()

expectTypeOf<Loading | Failed>().omit<'code'>().toEqualTypeOf<{state: 'loading' | 'failed'}>()
                                   // ^^^^^^ Type '"code"' does not satisfy the constraint '"state"'.
```

**Comment by mmkal** [comment]
@mrazauskas thanks for reporting. Note that `Omit<...>` doesn't seem to have any `extends` constraints at all (e.g. `Omit<{a: 1}, 'b'>` is allowed), so this will take away type hinting at which keys could/should be omitted. But I agree it's better to match `Omit`.

Would you be interested in submitting a pull request?

**Comment by aryaemami59** [comment]
> [mrazauskas](/mrazauskas)

Yes absolutely, I will take a look!
