### ISSUE TITLE
toEqualTypeOf not failing when it should

### ISSUE THREAD

**Issue by GuilhermeLessa** [mmkal/expect-type#57]
My vitest is testing all succes, but should not it fail as expected result?

` expectTypeOf({ a: 1 }).toEqualTypeOf<{ b: number }>({ b: 2 });`

![image](https://github.com/mmkal/expect-type/assets/8376833/62f57e76-0043-4b63-ac03-e1106cce280c)

![image](https://github.com/mmkal/expect-type/assets/8376833/0058000e-dce8-4c44-991c-e5a9dd269992)

vue 3.3.11
vite 5.1.5
vitest 1.3.1
expect-type 0.18.0
typescript 5.4.0

**Comment by mmkal** [comment]
Yep, alternatively you can just run `tsc` on your test files, but I believe vitest will give more helpful errors that include the test name etc.

Also, it'd be better to use the typearg only form:

```ts
expectTypeOf({ a: 1 }).toEqualTypeOf<{ b: number }>()
```

**Comment by GuilhermeLessa** [comment]
@mmkal @aryaemami59  yea I have these settings enabling typecheck... Anything else could I've forgotten?

```
export default mergeConfig(
  viteConfig,
  defineConfig({
    test: {
      environment: 'jsdom',
      exclude: [...configDefaults.exclude, 'e2e/*'],
      root: fileURLToPath(new URL('./', import.meta.url)),
      globals: true,
      typecheck: { enabled: true },
    }
  })
)
```
![image](https://github.com/mmkal/expect-type/assets/8376833/06933e39-0264-422b-bc86-4f782e644d50)
![image](https://github.com/mmkal/expect-type/assets/8376833/a6292aa6-2447-49e3-a3d1-f5378ca9e34f)

**Comment by mmkal** [comment]
I'm not sure, this is a question for https://github.com/vitest-dev/vitest. If you can still think there's something wrong with expect-type, feel free to open a new issue with a playground link ([like this](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwKYA8xIMYwCoE90DyAZgL5xFQQhwDkq6WAtDPkjQFDv2Y6vEAUCAIYAuOAEYSASgB0MCAFEAjgFchAGzyEiAHmFiAdipAAjJFBIA+flKA)).

**Comment by aryaemami59** [comment]
@GuilhermeLessa Yeah if you provide a reproduction I'm sure I can help.
