### ISSUE TITLE
[expect-type]: Allow negation of `toBeCallableWith`

### ISSUE THREAD

**Issue by GerkinDev** [mmkal/expect-type#6]
I've noticed it's impossible to check for a function to **not** be callable with arguments

https://github.com/mmkal/ts/blob/main/packages/expect-type/src/index.ts#L111

In case of negated assertion, the check property is `never`.

So. I've tweaked around and I think the issue is that typing errors are generated during the last call, where type parameters are merged to generate a `MISMATCH`, spread as a rest parameter to generate type that can never be instantiated properly. But the current format of `toBeCallableWith` already takes a rest parameter for args.

So, here is the proposal: create a new method that takes arguments not as a rest tuple, but as a single tuple. Something like this:

```ts
export interface ExpectTypeOf<Actual, B extends boolean> {
    toBeCallableWithArgs: <T extends any[] | [never]>(args: T, ...MISMATCH: MismatchArgs<Extends<T, Params<Actual>>, B>) => true;
}
```

Thoughts ?

**Comment by mmkal** [comment]
Yes, this would be nice, but unfortunately breaks down for overloaded functions. I'll leave this open so it can be documented better, but basically - you'll have to use `@ts-expect-error`.

**Comment by aryaemami59** [comment]
@mmkal I think I'm gonna give this a shot, it might be a good new feature for v1.
