### ISSUE TITLE
Add `test()` helper

### ISSUE THREAD

**Issue by mrazauskas** [mmkal/expect-type#63]
[Playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwKYA8xIMYwCoE90DyAZgL5xFQQhwDkq6WAtDPkjQFCiSyJEQQAaOACMAhlDIUqtAHQyA9Hwgd2MJAGcYAChpK4LdOppCtASjgBeAHyJ2cOPPlwQogNZI46gK5QPAAyU-OAALUXV9VkRRAC44ADsvEGEkCTs4ekwcVmItJVMZGAgAWVEYDGC8QiIAHgQY+MTkiSszdjTHZzcPb184PzEoIOBw0XIvOKxgCDj9N2A4gHM4Uc0oeYXotIysSqQcgfywcVEQJDUoLQAGfMKAISQAZRg1xdb7bayqrQOZXxgfOLqGRxCAwAoQe4AQTiuFaJFMQA)

Just to draw your attention, the first example in readme is not working. I have added playground link. It is rather obvious that `test()` is not imported.

Just an idea: perhaps `expect-type` could have its own `test()` helper?

**Comment by mmkal** [comment]
Thanks! That example assumes a globally available `test` value - it's from the jest days, but we should simplify so you can copy the example directly and have it work.
