### ISSUE TITLE
`.toHaveProperty()` does not distinguish between `any` and `never`

### ISSUE THREAD

**Issue by mrazauskas** [mmkal/expect-type#64]
[Playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwKYA8xIMYwCoE90DyAZgL5xFQQhwDkq6WAtDPkjQFDv2Y6vEA8AQwB2uAHwAKAJQA6GBAASggG5IACpXSxcEmkQgQaUgNxc0PPISL9hSVVEmz5S1RohaWu-YZOcMEYQBneAAjQSg4AF5EMkFAuFt7U3YwqBlvYyA)

`.toHaveProperty()` does not distinguish between `any` and `never`. See the link above.

It sound like `never` should not have any properties. Might be I missed something.

**Comment by aryaemami59** [comment]
@mrazauskas Technically both `keyof never` and `keyof any` resolve to `string | number | symbol`. Not sure if it would be the best idea to stray away from TypeScript's intended behavior but you're right. Semantically it doesn't make sense. It seems like `keyof never` should be `never`. Not sure what the best approach here would be to be honest.
