### ISSUE TITLE
Intersection types check fail

### ISSUE THREAD

**Issue by zzxming** [mmkal/expect-type#81]
Just like the introduction. It cannot pass typecheck. How can i make this work.

[Here is the reproduction](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwKYA8xIMYwCoE90DyAZgL5xFQQhwDkq6WAtDPkjQFDsvpzZIDOMADwE4qGEgB2AE35wASpmjShgqMEkBzADRwAhpNwA+I3AC8idnGtwA2gGk4GuAGskuCETgAFYBhciujR6NHAAPrQARjRGALoAXHAEDrHsZABkljZ2js5uHl4EIMDCBEEh4VExCXAArpIukhAA7pJpANycXKy8AIzmvALCCPqJ-SRGnfSYOKzEQti9RgAUAJQAdDAQAKIAjrV6ADZ4hERCI3pjcBNrU2gzJ0jziysbW3sHx3NnF2PtcJFEvVGi1JNdXncGLNTgslmtNjt9kdHvNfnBev9AXUGk1Wtc4JkEDdVp1ujxsAAmAZ8QTnUbo3RYqkTSEPb4LCmvBEfZHstEYgGJZkQ9jTLAos6UrnvJFfGH8zFC-GE4mk7hIXgAZmpQzplwZgrgFN0GES2pZovu4vZ2E10sRnwler+huZBMQcFN2JBeNVQA)

When I checked the props type in `Vue` with `ExtractPropTypes`, I found that the problem occurred when all the props are optional or required.

[Here is the reproduction about Vue](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBDAnmApnA3nAogDxlAQwGMYAFKCMAFWRQGc4BfOAMwpDgHIA3AVxU4AoUJFgY4KHKhI1UAeRZNW7LpOkwAtElRDBRCADs68MBTABGOAF4MguHADWKROYBccAMr5gBgOYAaO0dnACZ3dCD7bRR3ADleEAAjFChA+0ZA5gIGfSMYQWi4UksbXHxiMjNZegAeaIhFU0pzAD5BNRQZWgUa4paACgBKADoYCCwAR14CABtqnoj7KBQCABNDGcRglwB+d2MoH18g5bWNradEEL24AwTkqEFGAcH2qU6YeZZe1qHR8amsy+NUwzAAZLYlit1gZNttzDcDkcTtDzttru47kkUk8XoJ8bljHAmmAQtZIfD3F5Dn40ujwpEELQ4vcUnSMkFLgBmBn2KLMzzeWmM5ZTYDLVbufD8IKMJ5wbJwQn5QqkMmlPCEEjkSjVOh1WgNYlmEJtDpdeTfNUvf6TaZzbrfTAos6wi7OHlwJF+ODyiGLOCnGFwy4I-ZC45Q10h0I3LEPXFDQRAA)

**Comment by mrazauskas** [comment]
@zzxming Is this public project that you are testing?

Component prop type testing is something what I am trying to understand. So it would be interesting to see how you are doing that.

**Comment by zzxming** [comment]
> @zzxming Is this public project that you are testing?
> 
> Component prop type testing is something what I am trying to understand. So it would be interesting to see how you are doing that.

It's myself vue component. I just started writing the props test and I got this question. [if you want to see it](https://github.com/zzxming/cdx-component/blob/test/packages/utils/__tests__/props.test-d.ts)

**Comment by aryaemami59** [comment]
Hey sorry I didn't get to look at this today, I will take a look tomorrow. Thanks for the repro.

**Comment by mmkal** [comment]
This is a known limitation that affects some intersection types. Have a look at "why is my assertion failing?" In the readme. You should be able to use .branded to make it pass, at the cost of some tsc perf. Partial example from your playground (this made most pass, not sure what the intention is):

[updated playground](https://www.typescriptlang.org/play/?ssl=11&ssc=20&pln=11&pc=33#code/JYWwDg9gTgLgBAbwKYA8xIMYwCoE90DyAZgL5xFQQhwDkq6WAtDPkjQFDsvpzZIDOMADwE4qGEgB2AE35wASpmjShgqMEkBzADRwAhpNwA+I3AC8idnGtwA2gGk4GuAGskuCETgAFYBhciujR6NHAAPrQARjRGALoAXHAEDrHsZABkljZ2js5uHl4EIMDCBEEh4VExCXAArpIukhAA7pJpANycXKy8AIzmvALCCPqJ-SRGnfSYOKzEQti9RgAUAJQAdDAQAKIAjrV6ADZ4hERCI3pjcBNrU2gzJ0jziysbW3sHx3NnF2PtcJFEvVGi1JNdXncGLNTgslmtNjt9kdHvNfnBev9AXUGk1Wtc4JkEDdVp1ujxsAAmAZ8QTnUbo3RYqkTSEPb4LCmvBEfZHstEYgGJZkQ9jTLAos6UrnvJFfGH8zFC-GE4mk7hIXgAZmpQzplwZgrgFN0GES2pZovu4vZ2E10sRnwler+huZBMQcFN2JBeNVQA)

**Comment by zzxming** [comment]
> This is a known limitation that affects some intersection types. Have a look at "why is my assertion failing?" In the readme. You should be able to use .branded to make it pass, at the cost of some tsc perf. Partial example from your playground (this made most pass, but I'm on mobile rn and not sure what the intention is):
> 
> [updated playground](https://www.typescriptlang.org/play/?ssl=11&ssc=20&pln=11&pc=33#code/JYWwDg9gTgLgBAbwKYA8xIMYwCoE90DyAZgL5xFQQhwDkq6WAtDPkjQFDsvpzZIDOMADwE4qGEgB2AE35wASpmjShgqMEkBzADRwAhpNwA+I3AC8idnGtwA2gGk4GuAGskuCETgAFYBhciujR6NHAAPrQARjRGALoAXHAEDrHsZABkljZ2js5uHl4EIMDCBEEh4VExCXAArpIukhAA7pJpANycXKy8AIzmvALCCPqJ-SRGnfSYOKzEQti9RgAUAJQAdDAQAKIAjrV6ADZ4hERCI3pjcBNrU2gzJ0jziysbW3sHx3NnF2PtcJFEvVGi1JNdXncGLNTgslmtNjt9kdHvNfnBev9AXUGk1Wtc4JkEDdVp1ujxsAAmAZ8QTnUbo3RYqkTSEPb4LCmvBEfZHstEYgGJZkQ9jTLAos6UrnvJFfGH8zFC-GE4mk7hIXgAZmpQzplwZgrgFN0GES2pZovu4vZ2E10sRnwler+huZBMQcFN2JBeNVQA)

Sorry I'm not read the docs very well. `.branded` is work for my case. Thank you for your answer.
